//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniMerit.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public int Id { get; set; }
        public Nullable<int> Uid { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Password { get; set; }
        public string Class { get; set; }
        public string Board { get; set; }
    }
}
