//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnimerit.Data.Model.Database
{
    using System;
    using System.Collections.Generic;
    using Omnimerit.Data.BussinessLayer;
    using System.ComponentModel.DataAnnotations;
    
    public partial class AccountGroup
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "*Please enter Account Name")]
        public string AccountName { get; set; }

        [Required(ErrorMessage = "*Please Select a valid Group")]
        public string GroupUnder { get; set; }
        public string Status { get; set; }
    }
}
