//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnimerit.Data.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirResult
    {
        public double S_no { get; set; }
        public string Name { get; set; }
        public Nullable<double> Mobile_No { get; set; }
        public Nullable<double> State_Code { get; set; }
        public Nullable<double> Centre_Code { get; set; }
        public string Institute { get; set; }
        public Nullable<double> No_of_correct_response { get; set; }
        public Nullable<double> No_of_Incorrect_response { get; set; }
        public Nullable<double> No_of_responses_Left_Blank { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<float> Percentage { get; set; }
        public Nullable<double> AIR { get; set; }
        public Nullable<float> Percentile { get; set; }
        public Nullable<double> Kanpur_Rank { get; set; }
        public Nullable<double> Centre_Rank { get; set; }
        public Nullable<double> Attempt_Rate { get; set; }
        public Nullable<float> Accuracy { get; set; }
    }
}
