//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnimerit.Data.Model.Database
{
    using System;
    using System.Collections.Generic;
    using Omnimerit.Data.BussinessLayer;
    using System.ComponentModel.DataAnnotations;
    public partial class TransportAllocationDetail
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "*Please Select Route Code")]
        public string RouteCode { get; set; }

        [Required(ErrorMessage = "*Please Select Source")]
        public string Source { get; set; }

        [Required(ErrorMessage = "*Please Select Destination")]
        public string Destination { get; set; }

        [Required(ErrorMessage = "*Please Select User Type")]
        public string UserType { get; set; }

        [Required(ErrorMessage = "*Please Enter Name")]
        public string UserName { get; set; }


        [Required(ErrorMessage = "*Please enter Start Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> StartDate { get; set; }

        [Required(ErrorMessage = "*Please enter End Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
